services:

  mysql:
    image: mysql
    #        platform: linux/amd64
    container_name: mysql
    volumes:
      - ./:/app/server/mysql/
    environment:
      MYSQL_DATABASE: palette
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password  # 추가한 부분
    restart: always


  redis:
    image: redis
    container_name: redis
#    hostname: redis
    ports:
      - "6379:6379"


  spring:
    build:
      context: ./palette-spring
      dockerfile: Dockerfile
    container_name: spring
    volumes:
      - ./:/app/server/palette/palette-spring/
    ports:
      - 8080:8080
    expose:
      - 8080

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://3.135.94.237:3306/palette
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_REDIS_HOST: redis  # Redis 컨테이너의 이름
#      SPRING_REDIS_PORT: 6379

    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    restart: always


  django:
    build:
      context: ./palette-django
      dockerfile: Dockerfile
    container_name: django
    command:
      - bash
      - -c
      - |
        cd ./palette-django
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/server/palette/
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./palette-django/.env
    depends_on:
      - mysql
      - redis
    restart: always
