services:
  db:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379


  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springbootapp
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/demo
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db
      - redis